name: Workflow for CI/CD on branch main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup nodejs v14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: check node and npm versions
        run: |
          npm --version
          node --version

      - name: setup snyk
        run: |
          npm install -g snyk

      - name: auth on snyk
        run: |
          npm auth

      - name: run scan for vulnerabilities
        run: snyk test
