name: Workflow for CI/CD on branch main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup nodejs v14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: check node and npm versions
        run: |
          npm --version
          node --version

      - name: setup snyk
        with:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          echo $SNYK_TOKEN
          npm install -g snyk
          snyk auth $SNYK_TOKEN

      - name: run scan for vulnerabilities
        run: snyk test
