name: Workflow for CI/CD on branch main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup nodejs v14
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: check node and npm versions
      - run: npm --version
      - run: node --version
      - name: setup snyk
      - run: npm install -g snyk
      - run: snyk auth
      - name: run scan for vulnerabilities
      - run: snyk test
